/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.mavbraz.gui;

import javax.swing.ImageIcon;

/**
 *
 * @author mavbraz
 */
public class About extends javax.swing.JFrame {

    private final Main main;

    /**
     * Creates new form About
     *
     * @param main
     */
    public About(Main main) {
        this.main = main;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescription = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulado Detran/PE - Sobre");
        setIconImage(new ImageIcon(getClass().getResource("/detran-icon.png")).getImage());
        setResizable(false);

        lblDescription.setText("<html><body><center><h2>Simulado Detran - Versão 1.0</h2></center><hr><b>Descrição:</b><br><br>Programa, com 297 questões, criado com base  no simulador oficial do Detran/PE.<br><hr><b>Recursos e regras:</b><br><br>1. Simulado:<br>- Você terá 30 minutos para realizar a prova<br>- São necessários no mínimo 21 pontos para passar<br><br>2. Visualizar perguntas e repostas:<br>- Há a possibilidade de filtrar por categoria e pelo conteúdo de alguma pergunta<br><hr><b>Contato:</b><br><br>Criado por: Matheus Braz<br>E-mail: mavbraz@gmail.com<br>Github: https://github.com/mavbraz</body></html>");
        lblDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDescription.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        this.setVisible(false);
        main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel lblDescription;
    // End of variables declaration//GEN-END:variables
}
