/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.mavbraz.gui;

import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author mavbraz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblSimulado = new javax.swing.JLabel();
        lblPerguntas = new javax.swing.JLabel();
        lblSobre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulado Detran/PE");
        setIconImage(new ImageIcon(getClass().getResource("/detran-icon.png")).getImage());
        setResizable(false);

        lblLogo.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/detran-logo.png"))); // NOI18N
        lblLogo.setText("Simulado");
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblSimulado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSimulado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulado.png"))); // NOI18N
        lblSimulado.setText("Simulado");
        lblSimulado.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        lblSimulado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSimulado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSimulado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSimuladoMouseClicked(evt);
            }
        });

        lblPerguntas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPerguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizar.png"))); // NOI18N
        lblPerguntas.setText("Ver Perguntas");
        lblPerguntas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        lblPerguntas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPerguntas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblPerguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerguntasMouseClicked(evt);
            }
        });

        lblSobre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sobre.png"))); // NOI18N
        lblSobre.setText("Sobre");
        lblSobre.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        lblSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSobreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblSimulado)
                        .addGap(18, 18, 18)
                        .addComponent(lblPerguntas)
                        .addGap(18, 18, 18)
                        .addComponent(lblSobre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblLogo)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSimulado)
                    .addComponent(lblPerguntas)
                    .addComponent(lblSobre))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSobreMouseClicked
        this.setVisible(false);
        new About(this).setVisible(true);
    }//GEN-LAST:event_lblSobreMouseClicked

    private void lblPerguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerguntasMouseClicked
        this.setVisible(false);
        new Questions(this).setVisible(true);
    }//GEN-LAST:event_lblPerguntasMouseClicked

    private void lblSimuladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSimuladoMouseClicked
        this.setVisible(false);
        new Test(this).setVisible(true);
    }//GEN-LAST:event_lblSimuladoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPerguntas;
    private javax.swing.JLabel lblSimulado;
    private javax.swing.JLabel lblSobre;
    // End of variables declaration//GEN-END:variables
}
