package com.github.mavbraz.gui;

import com.github.mavbraz.hibernate.DetranFactory;
import com.github.mavbraz.hibernate.basic.Question;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.border.LineBorder;

/**
 *
 * @author mavbraz
 */
public class Test extends javax.swing.JFrame {

    private final Main main;
    private final JToggleButton[] questionsButtons = new JToggleButton[30];
    private final JToggleButton[] answersButtons = new JToggleButton[4];

    private Question[] questions;
    private int[] answers;
    private int currentQuestion;
    private boolean delivered;

    private Timer timer;
    private int remainTime;

    /**
     * Creates new form Test
     *
     * @param main
     */
    public Test(Main main) {
        this.main = main;

        initComponents();

        questionsButtons[0] = tbtn1;
        questionsButtons[1] = tbtn2;
        questionsButtons[2] = tbtn3;
        questionsButtons[3] = tbtn4;
        questionsButtons[4] = tbtn5;
        questionsButtons[5] = tbtn6;
        questionsButtons[6] = tbtn7;
        questionsButtons[7] = tbtn8;
        questionsButtons[8] = tbtn9;
        questionsButtons[9] = tbtn10;
        questionsButtons[10] = tbtn11;
        questionsButtons[11] = tbtn12;
        questionsButtons[12] = tbtn13;
        questionsButtons[13] = tbtn14;
        questionsButtons[14] = tbtn15;
        questionsButtons[15] = tbtn16;
        questionsButtons[16] = tbtn17;
        questionsButtons[17] = tbtn18;
        questionsButtons[18] = tbtn19;
        questionsButtons[19] = tbtn20;
        questionsButtons[20] = tbtn21;
        questionsButtons[21] = tbtn22;
        questionsButtons[22] = tbtn23;
        questionsButtons[23] = tbtn24;
        questionsButtons[24] = tbtn25;
        questionsButtons[25] = tbtn26;
        questionsButtons[26] = tbtn27;
        questionsButtons[27] = tbtn28;
        questionsButtons[28] = tbtn29;
        questionsButtons[29] = tbtn30;

        answersButtons[0] = tbtnA;
        answersButtons[1] = tbtnB;
        answersButtons[2] = tbtnC;
        answersButtons[3] = tbtnD;

        startTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        tbtn1 = new javax.swing.JToggleButton();
        tbtn2 = new javax.swing.JToggleButton();
        tbtn3 = new javax.swing.JToggleButton();
        tbtn4 = new javax.swing.JToggleButton();
        tbtn5 = new javax.swing.JToggleButton();
        tbtn6 = new javax.swing.JToggleButton();
        tbtn7 = new javax.swing.JToggleButton();
        tbtn8 = new javax.swing.JToggleButton();
        tbtn9 = new javax.swing.JToggleButton();
        tbtn10 = new javax.swing.JToggleButton();
        tbtn11 = new javax.swing.JToggleButton();
        tbtn12 = new javax.swing.JToggleButton();
        tbtn13 = new javax.swing.JToggleButton();
        tbtn14 = new javax.swing.JToggleButton();
        tbtn15 = new javax.swing.JToggleButton();
        tbtn16 = new javax.swing.JToggleButton();
        tbtn17 = new javax.swing.JToggleButton();
        tbtn18 = new javax.swing.JToggleButton();
        tbtn19 = new javax.swing.JToggleButton();
        tbtn20 = new javax.swing.JToggleButton();
        tbtn21 = new javax.swing.JToggleButton();
        tbtn22 = new javax.swing.JToggleButton();
        tbtn23 = new javax.swing.JToggleButton();
        tbtn24 = new javax.swing.JToggleButton();
        tbtn25 = new javax.swing.JToggleButton();
        tbtn26 = new javax.swing.JToggleButton();
        tbtn27 = new javax.swing.JToggleButton();
        tbtn28 = new javax.swing.JToggleButton();
        tbtn29 = new javax.swing.JToggleButton();
        tbtn30 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEntregar = new javax.swing.JButton();
        pContent = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        tbtnA = new javax.swing.JToggleButton();
        lblA = new javax.swing.JLabel();
        tbtnB = new javax.swing.JToggleButton();
        lblB = new javax.swing.JLabel();
        tbtnC = new javax.swing.JToggleButton();
        lblC = new javax.swing.JLabel();
        tbtnD = new javax.swing.JToggleButton();
        lblD = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        btnRefazerProva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulado Detran/PE - Simulado");
        setIconImage(new ImageIcon(getClass().getResource("/detran-icon.png")).getImage());
        setResizable(false);

        pMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblMenu.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblMenu.setText("Questões");

        buttonGroup1.add(tbtn1);
        tbtn1.setText("1");
        tbtn1.setFocusPainted(false);
        tbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn2);
        tbtn2.setText("2");
        tbtn2.setFocusPainted(false);
        tbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn3);
        tbtn3.setText("3");
        tbtn3.setFocusPainted(false);
        tbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn4);
        tbtn4.setText("4");
        tbtn4.setFocusPainted(false);
        tbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn5);
        tbtn5.setText("5");
        tbtn5.setFocusPainted(false);
        tbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn6);
        tbtn6.setText("6");
        tbtn6.setFocusPainted(false);
        tbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn7);
        tbtn7.setText("7");
        tbtn7.setFocusPainted(false);
        tbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn8);
        tbtn8.setText("8");
        tbtn8.setFocusPainted(false);
        tbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn9);
        tbtn9.setText("9");
        tbtn9.setFocusPainted(false);
        tbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn10);
        tbtn10.setText("10");
        tbtn10.setFocusPainted(false);
        tbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn11);
        tbtn11.setText("11");
        tbtn11.setFocusPainted(false);
        tbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn12);
        tbtn12.setText("12");
        tbtn12.setFocusPainted(false);
        tbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn13);
        tbtn13.setText("13");
        tbtn13.setFocusPainted(false);
        tbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn14);
        tbtn14.setText("14");
        tbtn14.setFocusPainted(false);
        tbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn15);
        tbtn15.setText("15");
        tbtn15.setFocusPainted(false);
        tbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn16);
        tbtn16.setText("16");
        tbtn16.setFocusPainted(false);
        tbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn16ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn17);
        tbtn17.setText("17");
        tbtn17.setFocusPainted(false);
        tbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn17ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn18);
        tbtn18.setText("18");
        tbtn18.setFocusPainted(false);
        tbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn18ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn19);
        tbtn19.setText("19");
        tbtn19.setFocusPainted(false);
        tbtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn19ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn20);
        tbtn20.setText("20");
        tbtn20.setFocusPainted(false);
        tbtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn21);
        tbtn21.setText("21");
        tbtn21.setFocusPainted(false);
        tbtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn21ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn22);
        tbtn22.setText("22");
        tbtn22.setFocusPainted(false);
        tbtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn22ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn23);
        tbtn23.setText("23");
        tbtn23.setFocusPainted(false);
        tbtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn23ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn24);
        tbtn24.setText("24");
        tbtn24.setFocusPainted(false);
        tbtn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn24ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn25);
        tbtn25.setText("25");
        tbtn25.setFocusPainted(false);
        tbtn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn25ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn26);
        tbtn26.setText("26");
        tbtn26.setFocusPainted(false);
        tbtn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn26ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn27);
        tbtn27.setText("27");
        tbtn27.setFocusPainted(false);
        tbtn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn27ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn28);
        tbtn28.setText("28");
        tbtn28.setFocusPainted(false);
        tbtn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn28ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn29);
        tbtn29.setText("29");
        tbtn29.setFocusPainted(false);
        tbtn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn29ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtn30);
        tbtn30.setText("30");
        tbtn30.setFocusPainted(false);
        tbtn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn30ActionPerformed(evt);
            }
        });

        btnEntregar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMenu)
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMenuLayout.createSequentialGroup()
                                .addComponent(tbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEntregar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn1)
                    .addComponent(tbtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn3)
                    .addComponent(tbtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn5)
                    .addComponent(tbtn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn7)
                    .addComponent(tbtn8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn9)
                    .addComponent(tbtn10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn11)
                    .addComponent(tbtn12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn13)
                    .addComponent(tbtn14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn15)
                    .addComponent(tbtn16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn17)
                    .addComponent(tbtn18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn19)
                    .addComponent(tbtn20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn21)
                    .addComponent(tbtn22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn23)
                    .addComponent(tbtn24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn25)
                    .addComponent(tbtn26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn27)
                    .addComponent(tbtn28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn29)
                    .addComponent(tbtn30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuestion.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tbtnA.setText("A");
        tbtnA.setEnabled(false);
        tbtnA.setFocusPainted(false);
        tbtnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnAActionPerformed(evt);
            }
        });

        lblA.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        tbtnB.setText("B");
        tbtnB.setEnabled(false);
        tbtnB.setFocusPainted(false);
        tbtnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnBActionPerformed(evt);
            }
        });

        lblB.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        tbtnC.setText("C");
        tbtnC.setEnabled(false);
        tbtnC.setFocusPainted(false);
        tbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnCActionPerformed(evt);
            }
        });

        lblC.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        tbtnD.setText("D");
        tbtnD.setEnabled(false);
        tbtnD.setFocusPainted(false);
        tbtnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDActionPerformed(evt);
            }
        });

        lblD.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        lblTempo.setText("Tempo restante: 00:00:00");

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        btnRefazerProva.setText("Refazer Prova");
        btnRefazerProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefazerProvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContentLayout = new javax.swing.GroupLayout(pContent);
        pContent.setLayout(pContentLayout);
        pContentLayout.setHorizontalGroup(
            pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pContentLayout.createSequentialGroup()
                        .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbtnB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pContentLayout.createSequentialGroup()
                        .addComponent(btnMenuPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefazerProva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTempo))
                    .addComponent(lblResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContentLayout.createSequentialGroup()
                        .addComponent(tbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContentLayout.createSequentialGroup()
                        .addComponent(tbtnD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pContentLayout.setVerticalGroup(
            pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnA, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblB, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tbtnB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnD, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempo)
                    .addComponent(btnRefazerProva)
                    .addComponent(btnMenuPrincipal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn1ActionPerformed
        moveToQuestion(1);
    }//GEN-LAST:event_tbtn1ActionPerformed

    private void tbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn2ActionPerformed
        moveToQuestion(2);
    }//GEN-LAST:event_tbtn2ActionPerformed

    private void tbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn3ActionPerformed
        moveToQuestion(3);
    }//GEN-LAST:event_tbtn3ActionPerformed

    private void tbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn4ActionPerformed
        moveToQuestion(4);
    }//GEN-LAST:event_tbtn4ActionPerformed

    private void tbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn5ActionPerformed
        moveToQuestion(5);
    }//GEN-LAST:event_tbtn5ActionPerformed

    private void tbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn6ActionPerformed
        moveToQuestion(6);
    }//GEN-LAST:event_tbtn6ActionPerformed

    private void tbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn7ActionPerformed
        moveToQuestion(7);
    }//GEN-LAST:event_tbtn7ActionPerformed

    private void tbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn8ActionPerformed
        moveToQuestion(8);
    }//GEN-LAST:event_tbtn8ActionPerformed

    private void tbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn9ActionPerformed
        moveToQuestion(9);
    }//GEN-LAST:event_tbtn9ActionPerformed

    private void tbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn10ActionPerformed
        moveToQuestion(10);
    }//GEN-LAST:event_tbtn10ActionPerformed

    private void tbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn11ActionPerformed
        moveToQuestion(11);
    }//GEN-LAST:event_tbtn11ActionPerformed

    private void tbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn12ActionPerformed
        moveToQuestion(12);
    }//GEN-LAST:event_tbtn12ActionPerformed

    private void tbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn13ActionPerformed
        moveToQuestion(13);
    }//GEN-LAST:event_tbtn13ActionPerformed

    private void tbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn14ActionPerformed
        moveToQuestion(14);
    }//GEN-LAST:event_tbtn14ActionPerformed

    private void tbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn15ActionPerformed
        moveToQuestion(15);
    }//GEN-LAST:event_tbtn15ActionPerformed

    private void tbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn16ActionPerformed
        moveToQuestion(16);
    }//GEN-LAST:event_tbtn16ActionPerformed

    private void tbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn17ActionPerformed
        moveToQuestion(17);
    }//GEN-LAST:event_tbtn17ActionPerformed

    private void tbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn18ActionPerformed
        moveToQuestion(18);
    }//GEN-LAST:event_tbtn18ActionPerformed

    private void tbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn19ActionPerformed
        moveToQuestion(19);
    }//GEN-LAST:event_tbtn19ActionPerformed

    private void tbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn20ActionPerformed
        moveToQuestion(20);
    }//GEN-LAST:event_tbtn20ActionPerformed

    private void tbtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn21ActionPerformed
        moveToQuestion(21);
    }//GEN-LAST:event_tbtn21ActionPerformed

    private void tbtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn22ActionPerformed
        moveToQuestion(22);
    }//GEN-LAST:event_tbtn22ActionPerformed

    private void tbtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn23ActionPerformed
        moveToQuestion(23);
    }//GEN-LAST:event_tbtn23ActionPerformed

    private void tbtn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn24ActionPerformed
        moveToQuestion(24);
    }//GEN-LAST:event_tbtn24ActionPerformed

    private void tbtn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn25ActionPerformed
        moveToQuestion(25);
    }//GEN-LAST:event_tbtn25ActionPerformed

    private void tbtn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn26ActionPerformed
        moveToQuestion(26);
    }//GEN-LAST:event_tbtn26ActionPerformed

    private void tbtn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn27ActionPerformed
        moveToQuestion(27);
    }//GEN-LAST:event_tbtn27ActionPerformed

    private void tbtn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn28ActionPerformed
        moveToQuestion(28);
    }//GEN-LAST:event_tbtn28ActionPerformed

    private void tbtn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn29ActionPerformed
        moveToQuestion(29);
    }//GEN-LAST:event_tbtn29ActionPerformed

    private void tbtn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn30ActionPerformed
        moveToQuestion(30);
    }//GEN-LAST:event_tbtn30ActionPerformed

    private void tbtnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnAActionPerformed
        setAnswer(1);
    }//GEN-LAST:event_tbtnAActionPerformed

    private void tbtnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnBActionPerformed
        setAnswer(2);
    }//GEN-LAST:event_tbtnBActionPerformed

    private void tbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCActionPerformed
        setAnswer(3);
    }//GEN-LAST:event_tbtnCActionPerformed

    private void tbtnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDActionPerformed
        setAnswer(4);
    }//GEN-LAST:event_tbtnDActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        if (!finishAnswers()) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Você deseja entregar a prova sem responder todas as questões?", "Aviso", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.NO_OPTION) {
                return;
            }
        }

        deliveryTest();
        timer.cancel();
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void btnRefazerProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefazerProvaActionPerformed
        if (!delivered) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Você deseja refazer a prova sem entregar a atual?", "Aviso", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.NO_OPTION) {
                return;
            }
        }

        startTest();
    }//GEN-LAST:event_btnRefazerProvaActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        if (!delivered) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Você deseja ir para o menu principal sem entregar a prova?", "Aviso", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.NO_OPTION) {
                return;
            }
        }
        
        this.setVisible(false);
        main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void startTest() {
        DetranFactory factory = new DetranFactory();
        questions = factory.getRandomQuestions(30).toArray(new Question[30]);
        answers = new int[30];

        tbtnA.setEnabled(true);
        tbtnB.setEnabled(true);
        tbtnC.setEnabled(true);
        tbtnD.setEnabled(true);
        
        lblResposta.setText("");

        if (delivered) {
            for (int i = 0; i < questions.length; i++) {
                resetQuestionsColor(i);
            }
        }

        delivered = false;
        btnEntregar.setEnabled(true);

        setQuestion(1);

        if (timer != null) {
            timer.cancel();
        }

        remainTime = 30 * 60;
        timer = new Timer();
        timer.scheduleAtFixedRate(new DeliveryTimer(), 0, 1000);
    }

    private void setQuestion(int question) {
        currentQuestion = question;

        questionsButtons[question - 1].setSelected(true);

        lblQuestion.setText("<html><body>" + questions[question - 1].getQuestion() + "</body></html>");

        if (questions[question - 1].getImage() != null && !questions[question - 1].getImage().equals("")) {
            ImageIcon placa = new ImageIcon(getClass().getResource("/placas/" + questions[question - 1].getImage()));

            lblQuestion.setIcon(placa);
        } else {
            lblQuestion.setIcon(null);
        }

        lblA.setText("<html><body>" + questions[question - 1].getAnswers().get(0).getAnswer() + "</body></html>");
        lblB.setText("<html><body>" + questions[question - 1].getAnswers().get(1).getAnswer() + "</body></html>");
        lblC.setText("<html><body>" + questions[question - 1].getAnswers().get(2).getAnswer() + "</body></html>");
        lblD.setText("<html><body>" + questions[question - 1].getAnswers().get(3).getAnswer() + "</body></html>");

        tbtnA.setSelected(false);
        tbtnB.setSelected(false);
        tbtnC.setSelected(false);
        tbtnD.setSelected(false);

        tbtnA.setBorder(null);
        tbtnB.setBorder(null);
        tbtnC.setBorder(null);
        tbtnD.setBorder(null);

        if (answers[currentQuestion - 1] > 0) {
            answersButtons[answers[currentQuestion - 1] - 1].setSelected(true);
            answersButtons[answers[currentQuestion - 1] - 1].setBorder(new LineBorder(Color.BLACK));
        }

        if (delivered) {
            showCorrectAnswer(question);
        }
    }

    private void moveToQuestion(int question) {
        if (currentQuestion != question) {
            setQuestion(question);
        }
    }

    private void setAnswer(int answer) {
        answers[currentQuestion - 1] = answer;

        moveToQuestion(currentQuestion < 30 ? currentQuestion + 1 : 1);
    }

    private void resetQuestionsColor(int index) {
        questionsButtons[index].setOpaque(false);
        questionsButtons[index].setBackground(null);
    }

    private void setQuestionsColor(int index, Color color) {
        questionsButtons[index].setOpaque(true);
        questionsButtons[index].setBackground(color);
    }

    private void showCorrectAnswer(int question) {
        lblResposta.setText("Resposta correta: " + (questions[question - 1].getAnswer() == 1 ? "A"
                : questions[question - 1].getAnswer() == 2 ? "B"
                : questions[question - 1].getAnswer() == 3 ? "C" : "D"));
    }

    private boolean finishAnswers() {
        for (int answer : answers) {
            if (answer == 0) {
                return false;
            }
        }
        return true;
    }

    private void deliveryTest() {
        int corrects = 0;

        delivered = true;
        btnEntregar.setEnabled(false);

        for (int i = 0; i < questions.length; i++) {
            if (questions[i].getAnswer() == answers[i]) {
                setQuestionsColor(i, Color.GREEN);
                corrects++;
            } else {
                setQuestionsColor(i, Color.RED);
            }
        }

        tbtnA.setEnabled(false);
        tbtnB.setEnabled(false);
        tbtnC.setEnabled(false);
        tbtnD.setEnabled(false);

        showCorrectAnswer(currentQuestion);

        if (corrects > 21) {
            JOptionPane.showMessageDialog(this, new JLabel("<html><body><h1 style='color: green;'>Passou!</h1><br>Você acertou " + corrects + " de 30.</body></html>", JLabel.CENTER), "Resultado", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, new JLabel("<html><body><h1 style='color: red;'>Não Passou.</h1><br>Você acertou " + corrects + " de 30.</body></html>", JLabel.CENTER), "Resultado", JOptionPane.PLAIN_MESSAGE);
        }
    }

    private class DeliveryTimer extends TimerTask {

        @Override
        public void run() {
            lblTempo.setText("Tempo restante: " + formatDuration(remainTime));

            if (remainTime <= 0) {
                deliveryTest();
                timer.cancel();
            } else {
                remainTime--;
            }
        }

        private String formatDuration(long seconds) {
            long absSeconds = Math.abs(seconds);
            String positive = String.format(
                    "%02d:%02d:%02d",
                    absSeconds / 3600,
                    (absSeconds % 3600) / 60,
                    absSeconds % 60);
            return seconds < 0 ? "-" + positive : positive;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnRefazerProva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pContent;
    private javax.swing.JPanel pMenu;
    private javax.swing.JToggleButton tbtn1;
    private javax.swing.JToggleButton tbtn10;
    private javax.swing.JToggleButton tbtn11;
    private javax.swing.JToggleButton tbtn12;
    private javax.swing.JToggleButton tbtn13;
    private javax.swing.JToggleButton tbtn14;
    private javax.swing.JToggleButton tbtn15;
    private javax.swing.JToggleButton tbtn16;
    private javax.swing.JToggleButton tbtn17;
    private javax.swing.JToggleButton tbtn18;
    private javax.swing.JToggleButton tbtn19;
    private javax.swing.JToggleButton tbtn2;
    private javax.swing.JToggleButton tbtn20;
    private javax.swing.JToggleButton tbtn21;
    private javax.swing.JToggleButton tbtn22;
    private javax.swing.JToggleButton tbtn23;
    private javax.swing.JToggleButton tbtn24;
    private javax.swing.JToggleButton tbtn25;
    private javax.swing.JToggleButton tbtn26;
    private javax.swing.JToggleButton tbtn27;
    private javax.swing.JToggleButton tbtn28;
    private javax.swing.JToggleButton tbtn29;
    private javax.swing.JToggleButton tbtn3;
    private javax.swing.JToggleButton tbtn30;
    private javax.swing.JToggleButton tbtn4;
    private javax.swing.JToggleButton tbtn5;
    private javax.swing.JToggleButton tbtn6;
    private javax.swing.JToggleButton tbtn7;
    private javax.swing.JToggleButton tbtn8;
    private javax.swing.JToggleButton tbtn9;
    private javax.swing.JToggleButton tbtnA;
    private javax.swing.JToggleButton tbtnB;
    private javax.swing.JToggleButton tbtnC;
    private javax.swing.JToggleButton tbtnD;
    // End of variables declaration//GEN-END:variables
}
